name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-22.04
    env:
      PLUGIN_SLUG: show-environment-in-editor
    steps:
    - uses: actions/checkout@v1

    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.2
        extensions: zip

    - name: Set Node Version
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npx wp-scripts build

    #- name: Install composer dependencies
    #  run: composer install --optimize-autoloader --no-dev
      
    #- name: WordPress Plugin Deploy
    #  if: startsWith(github.ref, 'refs/tags/')
    #  uses: 10up/action-wordpress-plugin-deploy@1.4.1
    #  env:
    #    SLUG: ${{env.PLUGIN_SLUG}}
    #    SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
    #    SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}

    - name: Release
      run: |
        mkdir -p ${{env.PLUGIN_SLUG}}
        rsync -av * ${{env.PLUGIN_SLUG}}/${{env.PLUGIN_SLUG}} --exclude ${{env.PLUGIN_SLUG}} --exclude node_modules --exclude .git --exclude .github --exclude .gitignore --exclude .editorconfig --exclude .prettierrc.js
        cd ${{env.PLUGIN_SLUG}}
        zip -r ../${{env.PLUGIN_SLUG}}.zip ${{env.PLUGIN_SLUG}}
        
    - uses: actions/upload-artifact@master
      with:
        name: ${{env.PLUGIN_SLUG}}
        path: ${{env.PLUGIN_SLUG}}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{env.PLUGIN_SLUG}}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
